{% set name = "nionswift-tool" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  skip: True  # [py2k]
  entry_points:
    - nionswift-tool = nion.nionswift_tool.command:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - numpy 1.14.*
  run:
    - python

about:
  home: http://github.com/nion-software/nionswift-tool
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "A native launcher for Nion Swift."
  dev_url: https://github.com/nion-software/nionswift-tool

extra:
  recipe-maintainers:
    - cmeyer
