# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Ny5CkAs5DpGM1+5WZF1SPG3Dq+CiiJpdtKWx0NDm6bvhOl9CShFa1TcMHrl6YEdp5qmELuXuiJa6pJy1Dxj0yVIg2H0s7aU7J/zFiE4LYknsfusYxF2BIsoBI3zN4y8BrSjB3YW7iPQ7KLiP2ompS70CGDqTzj3PTCV06/rx3c02dAjmtXz9RoHgWSCM+sSzrE20BWXKjBRgPo0Wk8947YNNubDz0xENLpUUOJC5pmc406nek+FrzPbVf7etNor5CnucjpyOfV08/X1kBOFJuaJYp9jawSs5kIjbFKuBkLOWsP7ExY3tzMsxhaQYErD18X89rytce8DVVaOJ2MqNSOMoKxLNPVXmJrwqDAFkgIMn+R5mOFFpNX/aFqJuGiWbgTWztoOqkl+QeUzjNfyWDSfssT1fk0K4D/8HMEylE0wRGxvJCTgJD+8BV84gWeLhbNBApQFcWqjQQUgV5IOUQ3fpKf81JKUODMB7GhL/v4cTfotdn8/YE/nVcBjIg4nJ9q4mgY8H1D/D6De8QlcETAaLdOrrKXyhsb3j0AdJUgqJe9jGAGWfGvF6WsaqX+e3q06mJ4F4eITG2d3t7yA00KgMX1NVkCTbWeAmaPHwAKAZGxxvu8DkJ+evRuAvoVVDG7ogZPOc2InWFN9P/SZ6kAU0ikW7uRia8xJrPTWwBm0="

matrix:
  include:
    - env: CONFIG=linux_python3.6 UPLOAD_PACKAGES=True PLATFORM=linux-64
      os: linux

    - env: CONFIG=linux_python3.7 UPLOAD_PACKAGES=True PLATFORM=linux-64
      os: linux

    - env: CONFIG=osx_python3.6 UPLOAD_PACKAGES=True PLATFORM=osx-64
      os: osx
      osx_image: xcode9.4

    - env: CONFIG=osx_python3.7 UPLOAD_PACKAGES=True PLATFORM=osx-64
      os: osx
      osx_image: xcode9.4

script:

  - if [[ ${PLATFORM} =~ .*osx.* ]]; then ./.travis/run_osx_build.sh; fi

  - if [[ ${PLATFORM} =~ .*linux.* ]]; then pip install shyaml --user && ./.travis/run_docker_build.sh; fi