github:
  user_or_org: nion-software
channels:
  targets:
  - [nion, main]
max_py_ver: '37'
travis:
  secure:
    BINSTAR_TOKEN: Ny5CkAs5DpGM1+5WZF1SPG3Dq+CiiJpdtKWx0NDm6bvhOl9CShFa1TcMHrl6YEdp5qmELuXuiJa6pJy1Dxj0yVIg2H0s7aU7J/zFiE4LYknsfusYxF2BIsoBI3zN4y8BrSjB3YW7iPQ7KLiP2ompS70CGDqTzj3PTCV06/rx3c02dAjmtXz9RoHgWSCM+sSzrE20BWXKjBRgPo0Wk8947YNNubDz0xENLpUUOJC5pmc406nek+FrzPbVf7etNor5CnucjpyOfV08/X1kBOFJuaJYp9jawSs5kIjbFKuBkLOWsP7ExY3tzMsxhaQYErD18X89rytce8DVVaOJ2MqNSOMoKxLNPVXmJrwqDAFkgIMn+R5mOFFpNX/aFqJuGiWbgTWztoOqkl+QeUzjNfyWDSfssT1fk0K4D/8HMEylE0wRGxvJCTgJD+8BV84gWeLhbNBApQFcWqjQQUgV5IOUQ3fpKf81JKUODMB7GhL/v4cTfotdn8/YE/nVcBjIg4nJ9q4mgY8H1D/D6De8QlcETAaLdOrrKXyhsb3j0AdJUgqJe9jGAGWfGvF6WsaqX+e3q06mJ4F4eITG2d3t7yA00KgMX1NVkCTbWeAmaPHwAKAZGxxvu8DkJ+evRuAvoVVDG7ogZPOc2InWFN9P/SZ6kAU0ikW7uRia8xJrPTWwBm0=
appveyor:
  secure:
    BINSTAR_TOKEN: YCXl78g7U9HSABZ6GYD4VrBGAFA6ieBueHfEW4d70LfpTvEESM09/RDNcQ2gK6pE
